### PR TITLE
implement ensure_resources for rewrite

### PR DESCRIPTION
**Pull request by moritzfriedrich**
implement ensure_resources for rewrites

### CODE REVIEW

**Comment by mleiner** [comment]
Hi!

Thank you for this PR.

Do you mind adding a spec test for this new parameter?

Maybe you can use `spec/defines/authenticator_spec.rb` as an example.

This would help me with validating and testing this improvement more quickly.

Thank you!

**Comment by moritzfriedrich** [comment]
Hello Manuel
I actually don't understand how I am supposed to write a spec test for `ensure_resources` based on the example.
If I understand it correctly, I would have to include a Hiera-YAML file with an example, because it does not have a default value for rewrite.
The spec test for rewrite has already been created in a previous pull request.

I have just noticed that the `ensure_resources` functionality is also identically present under `config.pp`. What is the reason for this?

**Comment by mleiner** [comment]
I believe that the ensure_resource parts of `init.pp` are duplicates from an incomplete move to `config.pp`. I removed them, tests still succeed.

I also took the time to apply the current version of PDK and its templates.

**Comment by mleiner** [comment]
I'll also add an ensure_resources for adding defaults in a second

**Comment by mleiner** [comment]
@moritzfriedrich I have released 1.3.1 to puppet forge containing both of your PRs and 1.3.0 to github containing only the pdk update.

Thank you!

**Comment by moritzfriedrich** [comment]
Many thanks to you too :)

**Pull request merged**
